version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/data/mysql
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - mysql
    links:
      - mysql:mysql
    env_file:
      - .env